import { Lead, LeadStatus, User } from '@/types';

export const mockLeads: Lead[] = [
  {
    id: '1',
    firstName: 'Jorge',
    lastName: 'Ruiz',
    email: 'jorge.ruiz@example.com',
    linkedInProfile: 'linkedin.com/in/jorgeruiz',
    visasOfInterest: ['O-1'],
    status: LeadStatus.PENDING,
    submittedAt: '02/02/2024, 2:45 PM',
    country: 'Mexico',
  },
  {
    id: '2',
    firstName: 'Bahar',
    lastName: 'Zamir',
    email: 'bahar.zamir@example.com',
    linkedInProfile: 'linkedin.com/in/baharzamir',
    visasOfInterest: ['EB-1A', 'O-1'],
    status: LeadStatus.PENDING,
    submittedAt: '02/02/2024, 2:45 PM',
    country: 'Mexico',
  },
  {
    id: '3',
    firstName: 'Mary',
    lastName: 'Lopez',
    email: 'mary.lopez@example.com',
    linkedInProfile: 'linkedin.com/in/marylopez',
    visasOfInterest: ['EB-2 NIW'],
    status: LeadStatus.PENDING,
    submittedAt: '02/02/2024, 2:45 PM',
    country: 'Brazil',
  },
  {
    id: '4',
    firstName: 'Li',
    lastName: 'Zijin',
    email: 'li.zijin@example.com',
    linkedInProfile: 'linkedin.com/in/lizijin',
    visasOfInterest: ['O-1', 'EB-1A'],
    status: LeadStatus.PENDING,
    submittedAt: '02/02/2024, 2:45 PM',
    country: 'South Korea',
  },
  {
    id: '5',
    firstName: 'Mark',
    lastName: 'Antonov',
    email: 'mark.antonov@example.com',
    linkedInProfile: 'linkedin.com/in/markantonov',
    visasOfInterest: ['I don\'t know'],
    status: LeadStatus.PENDING,
    submittedAt: '02/02/2024, 2:45 PM',
    country: 'Russia',
  },
  {
    id: '6',
    firstName: 'Jane',
    lastName: 'Ma',
    email: 'jane.ma@example.com',
    linkedInProfile: 'linkedin.com/in/janema',
    visasOfInterest: ['EB-2 NIW'],
    status: LeadStatus.PENDING,
    submittedAt: '02/02/2024, 2:45 PM',
    country: 'Mexico',
  },
  {
    id: '7',
    firstName: 'Anand',
    lastName: 'Jain',
    email: 'anand.jain@example.com',
    linkedInProfile: 'linkedin.com/in/anandjain',
    visasOfInterest: ['O-1'],
    status: LeadStatus.REACHED_OUT,
    submittedAt: '02/02/2024, 2:45 PM',
    country: 'Mexico',
  },
  {
    id: '8',
    firstName: 'Anna',
    lastName: 'Voronova',
    email: 'anna.voronova@example.com',
    linkedInProfile: 'linkedin.com/in/annavoronova',
    visasOfInterest: ['EB-1A'],
    status: LeadStatus.PENDING,
    submittedAt: '02/02/2024, 2:45 PM',
    country: 'France',
  },
  // Additional leads for pagination
  {
    id: '9',
    firstName: 'Sofia',
    lastName: 'Garcia',
    email: 'sofia.garcia@example.com',
    linkedInProfile: 'linkedin.com/in/sofiagarcia',
    visasOfInterest: ['O-1', 'EB-1A'],
    status: LeadStatus.PENDING,
    submittedAt: '02/03/2024, 9:15 AM',
    country: 'Spain',
  },
  {
    id: '10',
    firstName: 'Raj',
    lastName: 'Patel',
    email: 'raj.patel@example.com',
    linkedInProfile: 'linkedin.com/in/rajpatel',
    visasOfInterest: ['EB-2 NIW'],
    status: LeadStatus.PENDING,
    submittedAt: '02/03/2024, 10:33 AM',
    country: 'India',
  },
  {
    id: '11',
    firstName: 'Chen',
    lastName: 'Wei',
    email: 'chen.wei@example.com',
    linkedInProfile: 'linkedin.com/in/chenwei',
    visasOfInterest: ['EB-1A'],
    status: LeadStatus.REACHED_OUT,
    submittedAt: '02/03/2024, 11:45 AM',
    country: 'China',
  },
  {
    id: '12',
    firstName: 'Natalia',
    lastName: 'Kowalski',
    email: 'natalia.kowalski@example.com',
    linkedInProfile: 'linkedin.com/in/nataliakowalski',
    visasOfInterest: ['O-1'],
    status: LeadStatus.PENDING,
    submittedAt: '02/03/2024, 1:20 PM',
    country: 'Poland',
  },
  {
    id: '13',
    firstName: 'Ahmed',
    lastName: 'Hassan',
    email: 'ahmed.hassan@example.com',
    linkedInProfile: 'linkedin.com/in/ahmedhassan',
    visasOfInterest: ['I don\'t know'],
    status: LeadStatus.PENDING,
    submittedAt: '02/03/2024, 3:10 PM',
    country: 'Egypt',
  },
  {
    id: '14',
    firstName: 'Carlos',
    lastName: 'Mendoza',
    email: 'carlos.mendoza@example.com',
    linkedInProfile: 'linkedin.com/in/carlosmendoza',
    visasOfInterest: ['EB-2 NIW', 'O-1'],
    status: LeadStatus.PENDING,
    submittedAt: '02/04/2024, 8:45 AM',
    country: 'Mexico',
  },
  {
    id: '15',
    firstName: 'Olivia',
    lastName: 'Johnson',
    email: 'olivia.johnson@example.com',
    linkedInProfile: 'linkedin.com/in/oliviajohnson',
    visasOfInterest: ['EB-1A'],
    status: LeadStatus.REACHED_OUT,
    submittedAt: '02/04/2024, 9:30 AM',
    country: 'Canada',
  },
  {
    id: '16',
    firstName: 'Hiroshi',
    lastName: 'Tanaka',
    email: 'hiroshi.tanaka@example.com',
    linkedInProfile: 'linkedin.com/in/hiroshitanaka',
    visasOfInterest: ['O-1'],
    status: LeadStatus.PENDING,
    submittedAt: '02/04/2024, 10:15 AM',
    country: 'Japan',
  },
  {
    id: '17',
    firstName: 'Emma',
    lastName: 'Müller',
    email: 'emma.muller@example.com',
    linkedInProfile: 'linkedin.com/in/emmamuller',
    visasOfInterest: ['EB-2 NIW'],
    status: LeadStatus.PENDING,
    submittedAt: '02/04/2024, 11:20 AM',
    country: 'Germany',
  },
  {
    id: '18',
    firstName: 'Gabriel',
    lastName: 'Silva',
    email: 'gabriel.silva@example.com',
    linkedInProfile: 'linkedin.com/in/gabrielsilva',
    visasOfInterest: ['O-1', 'EB-1A'],
    status: LeadStatus.PENDING,
    submittedAt: '02/04/2024, 2:40 PM',
    country: 'Brazil',
  },
  {
    id: '19',
    firstName: 'Priya',
    lastName: 'Sharma',
    email: 'priya.sharma@example.com',
    linkedInProfile: 'linkedin.com/in/priyasharma',
    visasOfInterest: ['I don\'t know'],
    status: LeadStatus.PENDING,
    submittedAt: '02/04/2024, 4:15 PM',
    country: 'India',
  },
  {
    id: '20',
    firstName: 'Leo',
    lastName: 'Kim',
    email: 'leo.kim@example.com',
    linkedInProfile: 'linkedin.com/in/leokim',
    visasOfInterest: ['EB-1A'],
    status: LeadStatus.REACHED_OUT,
    submittedAt: '02/05/2024, 9:10 AM',
    country: 'South Korea',
  },
  {
    id: '21',
    firstName: 'Isabella',
    lastName: 'Rossi',
    email: 'isabella.rossi@example.com',
    linkedInProfile: 'linkedin.com/in/isabellarossi',
    visasOfInterest: ['O-1', 'EB-2 NIW'],
    status: LeadStatus.PENDING,
    submittedAt: '02/05/2024, 10:30 AM',
    country: 'Italy',
  },
  {
    id: '22',
    firstName: 'Mohammed',
    lastName: 'Al-Farsi',
    email: 'mohammed.alfarsi@example.com',
    linkedInProfile: 'linkedin.com/in/mohammedalfarsi',
    visasOfInterest: ['EB-1A'],
    status: LeadStatus.PENDING,
    submittedAt: '02/05/2024, 11:45 AM',
    country: 'UAE',
  },
  {
    id: '23',
    firstName: 'Sophie',
    lastName: 'Martin',
    email: 'sophie.martin@example.com',
    linkedInProfile: 'linkedin.com/in/sophiemartin',
    visasOfInterest: ['EB-2 NIW'],
    status: LeadStatus.PENDING,
    submittedAt: '02/05/2024, 2:15 PM',
    country: 'France',
  },
  {
    id: '24',
    firstName: 'Diego',
    lastName: 'Herrera',
    email: 'diego.herrera@example.com',
    linkedInProfile: 'linkedin.com/in/diegoherrera',
    visasOfInterest: ['O-1'],
    status: LeadStatus.PENDING,
    submittedAt: '02/05/2024, 3:30 PM',
    country: 'Chile',
  },
  {
    id: '25',
    firstName: 'Yuki',
    lastName: 'Yamamoto',
    email: 'yuki.yamamoto@example.com',
    linkedInProfile: 'linkedin.com/in/yukiyamamoto',
    visasOfInterest: ['EB-1A', 'O-1'],
    status: LeadStatus.REACHED_OUT,
    submittedAt: '02/06/2024, 8:50 AM',
    country: 'Japan',
  },
  {
    id: '26',
    firstName: 'Elena',
    lastName: 'Petrov',
    email: 'elena.petrov@example.com',
    linkedInProfile: 'linkedin.com/in/elenapetrov',
    visasOfInterest: ['I don\'t know'],
    status: LeadStatus.PENDING,
    submittedAt: '02/06/2024, 9:45 AM',
    country: 'Russia',
  },
  {
    id: '27',
    firstName: 'Oscar',
    lastName: 'Sanchez',
    email: 'oscar.sanchez@example.com',
    linkedInProfile: 'linkedin.com/in/oscarsanchez',
    visasOfInterest: ['EB-2 NIW'],
    status: LeadStatus.PENDING,
    submittedAt: '02/06/2024, 11:20 AM',
    country: 'Mexico',
  },
  {
    id: '28',
    firstName: 'Maya',
    lastName: 'Wong',
    email: 'maya.wong@example.com',
    linkedInProfile: 'linkedin.com/in/mayawong',
    visasOfInterest: ['O-1'],
    status: LeadStatus.PENDING,
    submittedAt: '02/06/2024, 1:40 PM',
    country: 'Singapore',
  },
  {
    id: '29',
    firstName: 'Lucas',
    lastName: 'Dubois',
    email: 'lucas.dubois@example.com',
    linkedInProfile: 'linkedin.com/in/lucasdubois',
    visasOfInterest: ['EB-1A'],
    status: LeadStatus.PENDING,
    submittedAt: '02/06/2024, 3:15 PM',
    country: 'France',
  },
  {
    id: '30',
    firstName: 'Aisha',
    lastName: 'Khan',
    email: 'aisha.khan@example.com',
    linkedInProfile: 'linkedin.com/in/aishakhan',
    visasOfInterest: ['I don\'t know', 'EB-2 NIW'],
    status: LeadStatus.REACHED_OUT,
    submittedAt: '02/07/2024, 9:10 AM',
    country: 'Pakistan',
  },
  {
    id: '31',
    firstName: 'Daniel',
    lastName: 'Costa',
    email: 'daniel.costa@example.com',
    linkedInProfile: 'linkedin.com/in/danielcosta',
    visasOfInterest: ['O-1'],
    status: LeadStatus.PENDING,
    submittedAt: '02/07/2024, 10:25 AM',
    country: 'Portugal',
  },
  {
    id: '32',
    firstName: 'Nina',
    lastName: 'Ivanova',
    email: 'nina.ivanova@example.com',
    linkedInProfile: 'linkedin.com/in/ninaivanova',
    visasOfInterest: ['EB-1A'],
    status: LeadStatus.PENDING,
    submittedAt: '02/07/2024, 11:50 AM',
    country: 'Bulgaria',
  },
];

export const mockUser: User = {
  id: '1',
  email: 'admin@tryalma.ai',
  name: 'Admin',
  role: 'admin',
}; 